title: <p align="center"> GovindraoKatture </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf/resume.pdf">Resume</a>
  <a href="https://github.com/sajankedia">GitHub</a>
  
  
  <br>
   I am working as a Sr. Soultion Architect - Inra, Cloud & DevOps
   <br>
   </p>
   
   
   theme: jekyll-theme-minimal
