title: <p align="center"> Govindrao Katture </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
   <a href="https://github.com/grk05">GitHub</a>
  
  <br>   
  I'm working on Senior Soultion Architect - Infra, Cloud and DevOps .
    <br>
  </p>



theme: jekyll-theme-minimal
